version: 2
project_name: smd
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go mod tidy

builds:
  - id: smd
    main: ./cmd/smd/
    binary: smd
    # export GIT_STATE=$(if git diff-index --quiet HEAD --; then echo 'clean'; else echo 'dirty'; fi)
    # export BUILD_HOST=$(hostname)
    # export GO_VERSION=$(go version | awk '{print $3}')
    # export BUILD_USER=$(whoami)
    ldflags:
      - "-X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3

    env:
      - CGO_ENABLED=0

  - id: smd-init
    main: ./cmd/smd-init/
    binary: smd-init
    ldflags:
      - "-X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3

    env:
      - CGO_ENABLED=0


  - id: smd-loader
    main: ./cmd/smd-loader/
    binary: smd-loader
    ldflags:
      - "-X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3


    env:
      - CGO_ENABLED=0

dockers_v2:
  - id: smd
    ids:
      - smd
      - smd-init
      - smd-loader
    images:
      - ghcr.io/openchami/{{.ProjectName}}
    tags:
      - latest
      - "{{ .Tag }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - --pull
    extra_files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - migrations/

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - migrations/*
      - LICENSE
      - CHANGELOG.md
      - README.md

nfpms:
        - id: smd
          formats: 
          - deb
          - rpm
          - apk
          maintainer: "Alex Lovell-Troy <alovelltroy@lanl.gov>"
          description: "SMD is a tool for managing the inventory of an HPC system.  Read more at https://www.openchami.org"
          homepage: "https://www.openchami.org"
          license: MIT
          section: utils
          priority: optional
          contents:
            - src: dist/smd_{{ .Os }}_{{ if eq .Arch "amd64" }}{{ .Arch }}_{{ .Amd64 }}{{ else if eq .Arch "arm64" }}{{ .Arch }}_{{ .Arm64 }}{{ else }}{{ .Arch }}{{ end }}/smd
              dst: /usr/local/bin/smd
            - src: dist/smd-init_{{ .Os }}_{{ if eq .Arch "amd64" }}{{ .Arch }}_{{ .Amd64 }}{{ else if eq .Arch "arm64" }}{{ .Arch }}_{{ .Arm64 }}{{ else }}{{ .Arch }}{{ end }}/smd-init
              dst: /usr/local/bin/smd-init
            - src: dist/smd-loader_{{ .Os }}_{{ if eq .Arch "amd64" }}{{ .Arch }}_{{ .Amd64 }}{{ else if eq .Arch "arm64" }}{{ .Arch }}_{{ .Arm64 }}{{ else }}{{ .Arch }}{{ end }}/smd-loader
              dst: /usr/local/bin/smd-loader
    
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  disable: "{{ if eq .Env.IS_PR_BUILD \"true\" }}true{{ else }}false{{ end }}"
  github:
    owner: OpenCHAMI
    name: smd
  name_template: 'v{{ .Version }}'
  prerelease: auto
  mode: replace

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
