# Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT

# NOTE: Must be configured either explicitly by the site administrator or
# implicitly via one of the OpenCHAMI deployment meta-configuration packages.

[Container]
Environment=HSM_URL=
Environment=SMD_DBUSER=
Environment=SMD_DBNAME=
Environment=SMD_DBHOST=
Environment=SMD_DBPORT=5432
Environment=SMD_DBOPTS=sslmode=disable

# NO AUTH
Environment=SMD_AUTH_AUDIENCES=
Environment=SMD_AUTH_BACKEND=
Environment=SMD_AUTH_ISSUER=
Environment=SMD_JWKS_URL=

# Example defaults
# Environment=HSM_URL=http://smd.demo.openchami.cluster:27779
# Environment=SMD_DBHOST=postgres.demo.openchami.cluster
# Environment=SMD_DBNAME=hmsds
# Environment=SMD_DBPORT=5432
# Environment=SMD_DBUSER=smd-user
# Environment=SMD_DBOPTS=sslmode=disable

# TOKENSMITH AUTH ENABLED
# Environment=SMD_AUTH_AUDIENCES=smd
# Environment=SMD_AUTH_BACKEND=tokensmith
# Environment=SMD_AUTH_ISSUER=http://tokensmith.demo.openchami.cluster:8080
# Environment=SMD_JWKS_URL=http://tokensmith.demo.openchami.cluster:8080/.well-known/jwks.json
